require("thdtt.plugins-setup")
require("thdtt.core.options")
require("thdtt.core.keymaps")
require("thdtt.core.colorscheme")
require("thdtt.plugins.comment")
require("thdtt.plugins.nvim-tree")
require("thdtt.plugins.lualine")
require("thdtt.plugins.telescope")
require("thdtt.plugins.nvim-cmp")
require("thdtt.plugins.lsp.mason")
require("thdtt.plugins.lsp.lspsaga")
require("thdtt.plugins.lsp.lspconfig")
require("thdtt.plugins.lsp.null-ls")
require("thdtt.plugins.autopairs")
require("thdtt.plugins.treesitter")
require("thdtt.plugins.gitsigns")

